### ISSUE TITLE
Roadmap to initial release

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZGen.jl#3]
Here are some things I'd like to see before we make an initial release of the package:
- [ ] Consider renaming the package to something like GenInferenceObjects.jl . InferenceObjects.jl is trying to offer useful storage functionality independent of ArviZ, and this package would exclusively offer conversion to InferenceObjects types, so this seems more appropriate.
- [ ] Add a proper conversion function. With the ArviZ naming convention, this would have a name like `from_gen`, but this isn't terribly descriptive. This is a good opportunity to think about what naming convention makes sense when conversion functions can live elsewhere. In particular, can we think of one that works regardless of where the function lives?
- [ ] Add tests and CI
- [ ] Add examples
- [ ] Add documentation
